FROM node:18-alpine as build

WORKDIR /app

COPY /package.json .

RUN yarn install

COPY . .

RUN yarn dev

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/<nginx-file-path>

CMD [ "nginx", "-g", "daemon --off;" ]