FROM node:18-alpine as build

WORKDIR /app

COPY /package.json .

RUN yarn install

COPY . .

RUN yarn build


# This next stage discards the first image and use the new one as the base image
FROM nginx:stable-alpine 

WORKDIR /app

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]